# Generated by Django 5.1.4 on 2024-12-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='chat_id',
            field=models.BigIntegerField(max_length=255),
        ),
    ]
